language: python
cache: pip
python:
  - "3.8"
install:
    - pip install pytest-mock
    - pip install requests-mock
    - pip install pytest-flask
    - pip install --editable .  
script:
  - pytest
  